exchange:
  binance:
    enabled: true
  kucoin:
    enabled: false

binance:
  key:
  secret:

kucoin:
  key:
  secret:
  passphrase:

config:
  symbols:
    - BTCUSDT
    - ETHUSDT
    - ETHBTC
  currencies:
    - BTC
    - ETH
    - USDT

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5432/crypto-trader
    username: crypto-trader
  jpa:
    hibernate:
      ddl-auto: update
